name: Run Unit Tests and Lint Files
'on':
  push:
    branches:
      - 'main'
      - 'features/**'
      - '!features/slint'
  workflow_dispatch:

jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'

      # Step 3: Debug Node.js version
      - name: Debug Node.js version
        run: node -v

      # Step 4: Debug npm version
      - name: Debug npm version
        run: npm -v

      # Step 5: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 6: List installed dependencies
      - name: List installed dependencies
        run: npm list --depth=0

      # Step 7: Print environment variables
      - name: Print environment variables
        run: printenv

      # Step 8: List files in the repository
      - name: List files in the repository
        run: ls -R

      # Step 9: Install dependencies, build, test and lint
      - name: build, test and lint
        run: |
          #npm run build
          npm run test
          npm run lint

      - name: push
        run: git push
